import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import React from "react";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/providers/ThemeProvider";

// Google Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Circular Fonts (must be statically declared)
const circularBook = localFont({
  src: "../public/fonts/CircularStd-Book.woff2",
  weight: "300",
  style: "normal",
  variable: "--font-circular-book",
});

const circularLight = localFont({
  src: "../public/fonts/CircularStd-Light.woff2",
  weight: "400",
  style: "normal",
  variable: "--font-circular-light",
});

const circularMedium = localFont({
  src: "../public/fonts/CircularStd-Medium.woff2",
  weight: "500",
  style: "normal",
  variable: "--font-circular-medium",
});

const circularBold = localFont({
  src: "../public/fonts/CircularStd-Bold.woff2",
  weight: "700",
  style: "normal",
  variable: "--font-circular-bold",
});

const circularBlack = localFont({
  src: "../public/fonts/CircularStd-Black.woff2",
  weight: "900",
  style: "normal",
  variable: "--font-circular-black",
});

const circularBookItalic = localFont({
  src: "../public/fonts/CircularStd-BookItalic.woff2",
  weight: "300",
  style: "normal",
  variable: "--font-circular-book-italic",
});

const circularLightItalic = localFont({
  src: "../public/fonts/CircularStd-Light Italic.woff2",
  weight: "400",
  style: "normal",
  variable: "--font-circular-light-italic",
});

const circularMediumItalic = localFont({
  src: "../public/fonts/CircularStd-MediumItalic.woff2",
  weight: "500",
  style: "normal",
  variable: "--font-circular-medium-italic",
});

const circularBoldItalic = localFont({
  src: "../public/fonts/CircularStd-BoldItalic.woff2",
  weight: "700",
  style: "normal",
  variable: "--font-circular-bold-italic",
});

const circularBlackItalic = localFont({
  src: "../public/fonts/CircularStd-BlackItalic.woff2",
  weight: "900",
  style: "normal",
  variable: "--font-circular-black-italic",
});

// Combine font variables
const fontVars = [
  geistSans.variable,
  geistMono.variable,
  circularBook.variable,
  circularLight.variable,
  circularMedium.variable,
  circularBold.variable,
  circularBlack.variable,
  circularBookItalic.variable,
  circularLightItalic.variable,
  circularMediumItalic.variable,
  circularBoldItalic.variable,
  circularBlackItalic.variable,
].join(" ");

export const metadata: Metadata = {
  title: "vsCharge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${fontVars} antialiased flex mx-auto`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          forcedTheme="light"
          disableTransitionOnChange
        >
          <main className="w-full">
            <Navbar />
            <div className="">{children}</div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
